# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
GET http://localhost:5000/api/customers

###
[
{
    "date_created": "Wed, 26 Sep 2018 20:03:23 GMT",
    "date_updated": "Wed, 26 Sep 2018 20:04:11 GMT",
    "idx": 1,
    "name": "테스트 1",
    "total_money": 600000,
    "total_payback_money": 200000
},
{
    "date_created": "Wed, 26 Sep 2018 20:03:23 GMT",
    "date_updated": "Wed, 26 Sep 2018 20:04:11 GMT",
    "idx": 2,
    "name": "테스트 2",
    "total_money": 900000,
    "total_payback_money": 100000
}
]

###
GET http://localhost:5000/api/histories

###
[
{
    "date_created": "Wed, 26 Sep 2018 20:07:37 GMT",
    "idx": 1,
    "memo": null,
    "money": 100000,
    "type": 1, // 0(false) -> 대출, 1(true) -> 상환
    "udx": 2
}
]
